language: node_js

sudo: required

node_js:
  - "8.11"

env:
  - CXX=g++-4.8

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8
      - software-properties-common

before_install:
  - export CXX="g++-4.8"
  - npm update
  - sudo apt update

install:
  - npm install -g npm@latest
  - npm install -g truffle
  - npm install -g solium
  - docker pull mythril/myth
#  - sudo apt install ruby-coveralls
  - npm install 

script:
  - npm run compile
  - npm run coverage 
  - npm run lint
  - docker run mythril/myth --truffle

notifications:
  slack:
    on_success: always
